---
- name: Update containers
  hosts: localhost
  become: true

  tasks:

  - name: Stop container
    docker_container:
      name: todoappwithlogin
      state: stopped
  - name: Delete container
    docker_container:
      name: todoappwithlogin
      state: absent
  - name: Download Web Application image
    docker_image:
      name: eugenefltk/todoappwithlogin
      pull: yes
  - name: Start Web Application container
    docker_container:
      name: todoappwithlogin
      image: eugenefltk/todoappwithlogin
      env:
        DB_HOST: mysql-db
        DB_PORT: 3306
        DB_USER: root
        DB_USER_PASSWORD: root
      ports:
        - "8080:8080"
      networks:
        - name: team7-network
      state: started
